"""add sale and sale_items tables

Revision ID: 8413ab3964fe
Revises: d5c596244c9d
Create Date: 2026-01-07 19:13:20.182070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8413ab3964fe'
down_revision: Union[str, Sequence[str], None] = 'd5c596244c9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_items_id'), 'sale_items', ['id'], unique=False)
    op.drop_index(op.f('ix_sales_items_id'), table_name='sales_items')
    op.drop_table('sales_items')
    op.alter_column('sales', 'total_amount',
               existing_type=sa.FLOAT(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'total_amount',
               existing_type=sa.FLOAT(precision=53),
               nullable=False)
    op.create_table('sales_items',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('FK__sales_ite__produ__14270015')),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name=op.f('FK__sales_ite__sale___1332DBDC')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__sales_it__3213E83F08313C4D'))
    )
    op.create_index(op.f('ix_sales_items_id'), 'sales_items', ['id'], unique=False)
    op.drop_index(op.f('ix_sale_items_id'), table_name='sale_items')
    op.drop_table('sale_items')
    # ### end Alembic commands ###
