"""add purchase module

Revision ID: 8577fc48cd17
Revises: f8bbbc8cce5f
Create Date: 2025-12-23 22:56:26.772962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8577fc48cd17'
down_revision: Union[str, Sequence[str], None] = 'f8bbbc8cce5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('purchases', sa.Column('total_amount', sa.Float(), nullable=True))
    op.add_column('purchases', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('purchases', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('FK__purchases__produ__0F624AF8'), 'purchases', type_='foreignkey')
    op.drop_column('purchases', 'cost_price')
    op.drop_column('purchases', 'date')
    op.drop_column('purchases', 'product_id')
    op.drop_column('purchases', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('purchases', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('purchases', sa.Column('date', sa.DATETIME(), autoincrement=False, nullable=True))
    op.add_column('purchases', sa.Column('cost_price', sa.FLOAT(precision=53), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('FK__purchases__produ__0F624AF8'), 'purchases', 'products', ['product_id'], ['id'])
    op.alter_column('purchases', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('purchases', 'created_at')
    op.drop_column('purchases', 'total_amount')
    op.drop_column('purchases', 'status')
    # ### end Alembic commands ###
